---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: default
spec:
  containers:
    - command: ["sleep", "infinity"]
      image: docker.io/library/alpine:latest
      imagePullPolicy: Always
      name: test-pod
      resources:
        limits:
          cpu: 500m
          memory: 512Mi
        requests:
          cpu: 250m
          memory: 256Mi
